<script setup lang="ts">
definePageMeta({
  layout: "admin",
  middleware: ["auth"],
});

const route = useRoute()
const reportId = route.params.id as string

const { data: report, status } = await useFetch(`/api/reports/${reportId}`, {
  server: false,
})
</script>

<template>
  <UDashboardPanel id="admin-report-detail">
    <template #header>
      <UDashboardNavbar :title="report?.title || 'Report'">
        <template #leading>
          <UDashboardSidebarCollapse />
          <UButton
            icon="i-lucide-arrow-left"
            color="neutral"
            variant="ghost"
            to="/admin/reports"
            class="mr-2"
          />
        </template>
      </UDashboardNavbar>
    </template>

    <template #body>
      <div v-if="status === 'pending'" class="flex justify-center py-12">
        <UIcon name="i-lucide-loader-circle" class="size-8 animate-spin text-muted" />
      </div>

      <div v-else-if="!report" class="text-center py-12">
        <UIcon name="i-lucide-bar-chart-3" class="size-12 text-muted mx-auto mb-2" />
        <p class="text-sm text-muted">Report not found</p>
      </div>

      <div v-else class="space-y-6">
        <!-- Report Info -->
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <StatCard
            label="Type"
            :value="report.type"
            icon="i-lucide-file-text"
            color="text-blue-500"
            bg="bg-blue-500/10"
          />
          <StatCard
            label="Farm"
            :value="report.farm?.name || 'Unknown'"
            icon="i-lucide-tractor"
            color="text-green-500"
            bg="bg-green-500/10"
          />
          <StatCard
            label="Generated By"
            :value="report.generatedBy?.name || report.generatedBy?.email || 'Unknown'"
            icon="i-lucide-user"
            color="text-amber-500"
            bg="bg-amber-500/10"
          />
          <StatCard
            label="Date"
            :value="formatDate(report.generatedAt)"
            icon="i-lucide-calendar"
            color="text-primary"
            bg="bg-primary/10"
          />
        </div>

        <!-- Download -->
        <UCard v-if="report.fileUrl">
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-3">
              <UIcon name="i-lucide-file-down" class="size-6 text-primary" />
              <div>
                <p class="font-medium text-highlighted">Download Report</p>
                <p class="text-sm text-muted">{{ report.fileUrl }}</p>
              </div>
            </div>
            <UButton
              :to="report.fileUrl"
              target="_blank"
              label="Download"
              icon="i-lucide-download"
            />
          </div>
        </UCard>
      </div>
    </template>
  </UDashboardPanel>
</template>
