<script setup lang="ts">
import type { TableColumn } from '@nuxt/ui'

definePageMeta({
  layout: "admin",
  middleware: ["auth"],
});

const { data: reports, status } = await useFetch("/api/reports", {
  server: false,
});

type Report = NonNullable<typeof reports.value>[number]

function viewReport(r: Report) {
  navigateTo(`/admin/reports/${r.id}`)
}

const deleteSingleMessage = (r: Report) => `Are you sure you want to delete report "${r.title}"?`
const deleteBulkMessage = (n: number) => `Are you sure you want to delete ${n} reports?`

const columns: TableColumn<Report>[] = [
  {
    accessorKey: 'title',
    header: 'Title',
  },
  {
    accessorKey: 'type',
    header: 'Type',
  },
  {
    id: 'farm',
    header: 'Farm',
    cell: ({ row }) => row.original.farm?.name || '\u2014'
  },
  {
    id: 'generatedBy',
    header: 'Generated By',
    cell: ({ row }) => row.original.generatedBy?.name || 'Unknown'
  },
  {
    accessorKey: 'generatedAt',
    header: 'Date',
    cell: ({ row }) => formatDate(row.original.generatedAt)
  },
  {
    id: 'download',
    header: '',
    cell: ({ row }) => row.original.fileUrl
      ? h(resolveComponent('UButton'), {
          to: row.original.fileUrl,
          target: '_blank',
          icon: 'i-lucide-download',
          size: 'xs',
          variant: 'ghost',
          color: 'neutral'
        })
      : null
  },
]
</script>

<template>
  <UDashboardPanel id="admin-reports">
    <template #header>
      <UDashboardNavbar title="Reports">
        <template #leading>
          <UDashboardSidebarCollapse />
        </template>
      </UDashboardNavbar>
    </template>

    <template #body>
      <DataTable
        :data="reports ?? []"
        :columns="columns"
        :loading="status === 'pending'"
        search-key="title"
        search-placeholder="Search reports..."
        empty-icon="i-lucide-bar-chart-3"
        empty-text="No reports generated yet"
        name-key="title"
        delete-title="Delete Reports"
        :delete-single-message="deleteSingleMessage"
        :delete-bulk-message="deleteBulkMessage"
        hide-delete-btn
        @row-click="viewReport"
      />
    </template>
  </UDashboardPanel>
</template>
